// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Redirector.Tests.ReturnsUnprocessableContentFeature
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class КакПользовательЯМогуПопытатьсяОткрытьВБраузереУмнуюСсылкуДляКоторойНевозможноОпреелитьРедиректИУвидеть422ОшибкуЧтобыПонятьЧтоДляУмнойСсылкиПравилаОпределеныНоИхНевозможноОбработать_Feature : object, Xunit.IClassFixture<КакПользовательЯМогуПопытатьсяОткрытьВБраузереУмнуюСсылкуДляКоторойНевозможноОпреелитьРедиректИУвидеть422ОшибкуЧтобыПонятьЧтоДляУмнойСсылкиПравилаОпределеныНоИхНевозможноОбработать_Feature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ReturnsUnprocessableContent.feature"
#line hidden
        
        public КакПользовательЯМогуПопытатьсяОткрытьВБраузереУмнуюСсылкуДляКоторойНевозможноОпреелитьРедиректИУвидеть422ОшибкуЧтобыПонятьЧтоДляУмнойСсылкиПравилаОпределеныНоИхНевозможноОбработать_Feature(КакПользовательЯМогуПопытатьсяОткрытьВБраузереУмнуюСсылкуДляКоторойНевозможноОпреелитьРедиректИУвидеть422ОшибкуЧтобыПонятьЧтоДляУмнойСсылкиПравилаОпределеныНоИхНевозможноОбработать_Feature.FixtureData fixtureData, Redirector_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru-RU"), "ReturnsUnprocessableContentFeature", "Как пользователь, я могу попытаться открыть в браузере умную ссылку, для которой " +
                    "невозможно опреелить редирект, и увидеть 422 ошибку, чтобы понять, что для умной" +
                    " ссылки правила определены, но их невозможно обработать.", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Приложение отвечает 422 Unprocessable Content ошибкой на GET запрос, если правила" +
            " редиректа умной ссылки определяют, что ее редирект временно приостановлен")]
        [Xunit.TraitAttribute("FeatureTitle", "Как пользователь, я могу попытаться открыть в браузере умную ссылку, для которой " +
            "невозможно опреелить редирект, и увидеть 422 ошибку, чтобы понять, что для умной" +
            " ссылки правила определены, но их невозможно обработать.")]
        [Xunit.TraitAttribute("Description", "Приложение отвечает 422 Unprocessable Content ошибкой на GET запрос, если правила" +
            " редиректа умной ссылки определяют, что ее редирект временно приостановлен")]
        public void ПриложениеОтвечает422UnprocessableContentОшибкойНаGETЗапросЕслиПравилаРедиректаУмнойСсылкиОпределяютЧтоЕеРедиректВременноПриостановлен()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Приложение отвечает 422 Unprocessable Content ошибкой на GET запрос, если правила" +
                    " редиректа умной ссылки определяют, что ее редирект временно приостановлен", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
    testRunner.Given("Правила редиректа умной ссылки /freezed определяют, что ее редирект временно прио" +
                        "становлен", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line hidden
#line 6
    testRunner.When("Клиент отправляет GET-запрос на url /freezed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
#line 7
    testRunner.Then("Приложение отвечает 422 Unprocessable Content ошибкой", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Приложение не отвечает 422 Unprocessable Content ошибкой на GET запрос, если прав" +
            "ила редиректа умной ссылки определяют, что ее редирект не был временно приостано" +
            "влен")]
        [Xunit.TraitAttribute("FeatureTitle", "Как пользователь, я могу попытаться открыть в браузере умную ссылку, для которой " +
            "невозможно опреелить редирект, и увидеть 422 ошибку, чтобы понять, что для умной" +
            " ссылки правила определены, но их невозможно обработать.")]
        [Xunit.TraitAttribute("Description", "Приложение не отвечает 422 Unprocessable Content ошибкой на GET запрос, если прав" +
            "ила редиректа умной ссылки определяют, что ее редирект не был временно приостано" +
            "влен")]
        public void ПриложениеНеОтвечает422UnprocessableContentОшибкойНаGETЗапросЕслиПравилаРедиректаУмнойСсылкиОпределяютЧтоЕеРедиректНеБылВременноПриостановлен()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Приложение не отвечает 422 Unprocessable Content ошибкой на GET запрос, если прав" +
                    "ила редиректа умной ссылки определяют, что ее редирект не был временно приостано" +
                    "влен", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
    testRunner.Given("Правила редиректа умной ссылки /unfreezed не приостанавливают временно ее редирек" +
                        "т", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line hidden
#line 11
    testRunner.When("Клиент отправляет GET-запрос на url /unfreezed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line hidden
#line 12
    testRunner.Then("Приложение не отвечает 422 Unprocessable Content ошибкой", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                КакПользовательЯМогуПопытатьсяОткрытьВБраузереУмнуюСсылкуДляКоторойНевозможноОпреелитьРедиректИУвидеть422ОшибкуЧтобыПонятьЧтоДляУмнойСсылкиПравилаОпределеныНоИхНевозможноОбработать_Feature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                КакПользовательЯМогуПопытатьсяОткрытьВБраузереУмнуюСсылкуДляКоторойНевозможноОпреелитьРедиректИУвидеть422ОшибкуЧтобыПонятьЧтоДляУмнойСсылкиПравилаОпределеныНоИхНевозможноОбработать_Feature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
